server:
  port: 7979
  servlet:
    context-path: /
  shutdown: graceful
  http:
    port: 7979

spring:
  config:
    import: optional:classpath:.env[.properties]
  activate:
    on-profile: local
  ############################################################
  # DataSource 설정
  ############################################################\
  datasource:
    hikari:
      primary:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jdbc-url: ${PRIMARY_DB_URL}
        username: ${PRIMARY_DB_USERNAME}
        password: ${PRIMARY_DB_PASSWORD}
        connectionTimeout: 5000
        validationTimeout: 10000
        idleTimeout: 10000
        maxLifetime: 60000
        minimumIdle: 5
        maximumPoolSize: 10
      secondary:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jdbc-url: ${SECONDARY_DB_URL}
        username: ${SECONDARY_DB_USERNAME}
        password: ${SECONDARY_DB_PASSWORD}
        connectionTimeout: 5000
        validationTimeout: 10000
        idleTimeout: 10000
        maxLifetime: 60000
        minimumIdle: 5
        maximumPoolSize: 10
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

#  ############################################################
#  # Restful Client Configuration
#  ############################################################
#  restTemplate:
#    factory:
#      readTimeout: 60000
#      connectTimeout: 60000
#    httpClient:
#      maxConnTotal: 100
#      maxConnPerRoute: 5